{
  "openapi": "3.0.0",
  "x-stoplight": {
    "id": "291epccbgj72d"
  },
  "info": {
    "title": "CharVstack-API",
    "version": "1.0"
  },
  "servers": [],
  "paths": {
    "/api/v1/vms": {
      "post": {
        "summary": "Create a new VM",
        "operationId": "post-api-v1-vms",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "memory": {
                    "type": "integer"
                  },
                  "vcpu": {
                    "type": "integer"
                  }
                },
                "required": ["name", "memory", "vcpu"]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "ubuntu20.04",
                    "memory": 2048,
                    "vcpu": 4
                  }
                }
              }
            }
          }
        },
        "tags": ["vm"],
        "description": "VMを作成する",
        "responses": {
          "200": {
            "$ref": "#/components/responses/PostCreateNewVM200Response"
          }
        }
      },
      "get": {
        "summary": "Get all VMs list",
        "responses": {
          "200": {
            "$ref": "#/components/responses/GetAllVMsList200Response"
          }
        },
        "operationId": "get-api-v1-vms",
        "tags": ["vm"],
        "description": "全てのVM一覧を取得する"
      },
      "parameters": []
    },
    "/api/v1/vms/{vmId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "vmId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get a VM",
        "tags": ["vm"],
        "responses": {
          "200": {
            "$ref": "#/components/responses/GetVMByVMId200Response"
          }
        },
        "operationId": "get-api-v1-vms-:vmId",
        "description": "個々のVM情報を取得する"
      },
      "patch": {
        "summary": "Update a VM",
        "operationId": "patch-api-v1-vms-:vmId",
        "responses": {
          "200": {
            "$ref": "#/components/responses/PatchUpdateVMByVMId200Response"
          }
        },
        "tags": ["vm"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "memory": {
                    "type": "integer"
                  },
                  "vcpu": {
                    "type": "integer"
                  }
                }
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "centos_stream",
                    "memory": 1024,
                    "vcpu": 2
                  }
                }
              }
            }
          }
        },
        "description": "VM情報を更新する"
      }
    },
    "/api/v1/host": {
      "get": {
        "summary": "Get a host",
        "tags": ["host"],
        "responses": {
          "200": {
            "$ref": "#/components/responses/GetHost200Response"
          }
        },
        "operationId": "get-api-v1-host",
        "description": "ホスト情報を取得する"
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "Vm": {
        "title": "Vm",
        "type": "object",
        "x-tags": ["vm"],
        "description": "仮想マシンを表すモデル",
        "x-examples": {
          "default": {
            "name": "ubuntu20.04",
            "metadata": {
              "id": "4e0a3c48-f483-422a-b520-2820207cef42",
              "api_version": "v1"
            },
            "memory": 2048,
            "vcpu": 4,
            "devices": {
              "disk": [
                {
                  "type": "qcow2",
                  "path": "/var/lib/libvirt/images/ubuntu22.04.qcow2"
                }
              ]
            }
          }
        },
        "properties": {
          "name": {
            "type": "string"
          },
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          },
          "memory": {
            "type": "integer"
          },
          "vcpu": {
            "type": "integer"
          },
          "devices": {
            "$ref": "#/components/schemas/Devices"
          }
        },
        "required": ["name", "metadata", "memory", "vcpu", "devices"]
      },
      "Cpu": {
        "title": "Cpu",
        "type": "object",
        "x-tags": ["host"],
        "x-examples": {
          "default": {
            "counts": 4,
            "percent": 5
          }
        },
        "description": "ホストのCPU情報",
        "properties": {
          "counts": {
            "type": "integer"
          },
          "percent": {
            "type": "number",
            "format": "double"
          }
        },
        "required": ["counts", "percent"]
      },
      "Memory": {
        "title": "Memory",
        "type": "object",
        "x-tags": ["host"],
        "x-examples": {
          "default": {
            "total": 16526876672,
            "used": 8849772544,
            "free": 315400192,
            "used_percent": 53.54776174371394
          }
        },
        "description": "ホストのメモリ情報",
        "properties": {
          "total": {
            "type": "integer",
            "format": "uint64"
          },
          "used": {
            "type": "integer",
            "format": "uint64"
          },
          "free": {
            "type": "integer",
            "format": "uint64"
          },
          "used_percent": {
            "type": "number",
            "format": "double"
          }
        },
        "required": ["total", "used", "free", "used_percent"]
      },
      "StoragePool": {
        "title": "StoragePool",
        "type": "object",
        "x-tags": ["host"],
        "x-examples": {
          "default": {
            "name": "string",
            "total_size": 1006530654208,
            "used_size": 371360915456,
            "path": "string",
            "status": "Active"
          }
        },
        "description": "ホストが持つストレージプールの情報",
        "properties": {
          "name": {
            "type": "string"
          },
          "total_size": {
            "type": "integer",
            "format": "uint64"
          },
          "used_size": {
            "type": "integer",
            "format": "uint64"
          },
          "path": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": ["Active", "Error"]
          }
        },
        "required": ["name", "total_size", "used_size", "path", "status"]
      },
      "Disk": {
        "title": "Disk",
        "x-stoplight": {
          "id": "tlkfws9brap8f"
        },
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["unknown", "qcow2"]
          },
          "device": {
            "type": "string",
            "enum": ["disk", "cdrom", "unknown"]
          },
          "path": {
            "type": "string"
          }
        },
        "required": ["type", "device", "path"]
      },
      "Devices": {
        "title": "Devices",
        "x-stoplight": {
          "id": "ygi3yz6kih90l"
        },
        "type": "object",
        "properties": {
          "disk": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Disk"
            }
          }
        },
        "required": ["disk"]
      },
      "Metadata": {
        "title": "Metadata",
        "x-stoplight": {
          "id": "rpl1wy0d2lxgs"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "api_version": {
            "type": "string"
          }
        },
        "required": ["id", "api_version"]
      },
      "Host": {
        "title": "Host",
        "x-stoplight": {
          "id": "lvp4m819yoen7"
        },
        "type": "object",
        "properties": {
          "cpu": {
            "$ref": "#/components/schemas/Cpu"
          },
          "mem": {
            "$ref": "#/components/schemas/Memory"
          },
          "storage_pools": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/StoragePool"
            }
          }
        },
        "required": ["cpu", "mem", "storage_pools"]
      }
    },
    "responses": {
      "GetAllVMsList200Response": {
        "description": "全てのVM一覧",
        "content": {
          "application/json": {
            "schema": {
              "x-examples": {
                "example-1": {
                  "vms": [
                    {
                      "name": "ubuntu",
                      "metadata": {
                        "id": "4e0a3c48-f483-422a-b520-2820207cef42",
                        "api_version": "v1"
                      },
                      "memory": 2048,
                      "vcpu": 4,
                      "devices": {
                        "disk": [
                          {
                            "type": "qcow2",
                            "device": "disk",
                            "path": "/var/lib/libvirt/images/ubuntu22.04.qcow2"
                          }
                        ]
                      }
                    }
                  ]
                }
              },
              "type": "object",
              "properties": {
                "vms": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Vm"
                  }
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "vms": [
                    {
                      "name": "ubuntu",
                      "metadata": {
                        "id": "4e0a3c48-f483-422a-b520-2820207cef42",
                        "api_version": "v1"
                      },
                      "memory": 2048,
                      "vcpu": 4,
                      "devices": {
                        "disk": [
                          {
                            "type": "qcow2",
                            "device": "disk",
                            "path": "/var/lib/libvirt/images/ubuntu22.04.qcow2"
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "PostCreateNewVM200Response": {
        "description": "新規作成されたVM情報",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Vm"
            },
            "examples": {
              "example-1": {
                "value": {
                  "name": "ubuntu",
                  "metadata": {
                    "id": "4e0a3c48-f483-422a-b520-2820207cef42",
                    "api_version": "v1"
                  },
                  "memory": 2048,
                  "vcpu": 4,
                  "devices": {
                    "disk": [
                      {
                        "type": "qcow2",
                        "device": "disk",
                        "path": "/var/lib/libvirt/images/ubuntu22.04.qcow2"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "GetVMByVMId200Response": {
        "description": "VMIdに合致するVM情報",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Vm"
            },
            "examples": {
              "example-1": {
                "value": {
                  "name": "ubuntu",
                  "metadata": {
                    "id": "4e0a3c48-f483-422a-b520-2820207cef42",
                    "api_version": "v1"
                  },
                  "memory": 2048,
                  "vcpu": 4,
                  "devices": {
                    "disk": [
                      {
                        "type": "qcow2",
                        "device": "disk",
                        "path": "/var/lib/libvirt/images/ubuntu22.04.qcow2"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "PatchUpdateVMByVMId200Response": {
        "description": "更新されたVM情報",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Vm"
            },
            "examples": {
              "example-1": {
                "value": {
                  "name": "ubuntu",
                  "metadata": {
                    "id": "4e0a3c48-f483-422a-b520-2820207cef42",
                    "api_version": "v1"
                  },
                  "memory": 2048,
                  "vcpu": 4,
                  "devices": {
                    "disk": [
                      {
                        "type": "qcow2",
                        "device": "disk",
                        "path": "/var/lib/libvirt/images/ubuntu22.04.qcow2"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "GetHost200Response": {
        "description": "ホストの情報",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Host"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "vm"
    },
    {
      "name": "host"
    },
    {
      "name": "type"
    }
  ]
}
